// Generated by gencpp from file lidar_project/lidar.msg
// DO NOT EDIT!


#ifndef LIDAR_PROJECT_MESSAGE_LIDAR_H
#define LIDAR_PROJECT_MESSAGE_LIDAR_H

#include <ros/service_traits.h>


#include <lidar_project/lidarRequest.h>
#include <lidar_project/lidarResponse.h>


namespace lidar_project
{

struct lidar
{

typedef lidarRequest Request;
typedef lidarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lidar
} // namespace lidar_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidar_project::lidar > {
  static const char* value()
  {
    return "876c4429855d6020f9989528c5e136d4";
  }

  static const char* value(const ::lidar_project::lidar&) { return value(); }
};

template<>
struct DataType< ::lidar_project::lidar > {
  static const char* value()
  {
    return "lidar_project/lidar";
  }

  static const char* value(const ::lidar_project::lidar&) { return value(); }
};


// service_traits::MD5Sum< ::lidar_project::lidarRequest> should match
// service_traits::MD5Sum< ::lidar_project::lidar >
template<>
struct MD5Sum< ::lidar_project::lidarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidar_project::lidar >::value();
  }
  static const char* value(const ::lidar_project::lidarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar_project::lidarRequest> should match
// service_traits::DataType< ::lidar_project::lidar >
template<>
struct DataType< ::lidar_project::lidarRequest>
{
  static const char* value()
  {
    return DataType< ::lidar_project::lidar >::value();
  }
  static const char* value(const ::lidar_project::lidarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidar_project::lidarResponse> should match
// service_traits::MD5Sum< ::lidar_project::lidar >
template<>
struct MD5Sum< ::lidar_project::lidarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidar_project::lidar >::value();
  }
  static const char* value(const ::lidar_project::lidarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar_project::lidarResponse> should match
// service_traits::DataType< ::lidar_project::lidar >
template<>
struct DataType< ::lidar_project::lidarResponse>
{
  static const char* value()
  {
    return DataType< ::lidar_project::lidar >::value();
  }
  static const char* value(const ::lidar_project::lidarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAR_PROJECT_MESSAGE_LIDAR_H
